server:
  port: 8001
  servlet:
    context-path: /book-service

    
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        cache:
          use_second_level_cache: true
          provider_class: org.hibernate.cache.EhCacheProvider
          region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/book
    username: root
    password: root1234
    hikari:
      maximum-pool-size: 20
      connection-timeout: 10000
      idle-timeout: 300000
      minimum-idle: 5
      max-lifetime: 7200000
      auto-commit: true    